/**
 * Two settings that live together: what the adapter emits, and whether it
 * still needs a model to produce it.
 *
 * The rule is generated by the model once and only stored when it reproduces
 * the target on the adapter's own sample payload, so enabling it is a safe
 * choice rather than a leap of faith.
 */

'use client';

import { useState, useTransition } from 'react';
import { useTranslations } from 'next-intl';
import {
  deleteJsonataRule,
  generateJsonataRule,
  setJsonataEnabled,
  setOutputFormat,
} from '@/lib/actions';
import { useToast } from '@/components/ui/ToastProvider';

const FORMATS = [
  { id: 'json', label: 'JSON' },
  { id: 'xml', label: 'XML' },
  { id: 'csv', label: 'CSV' },
] as const;

export function OutputRuleCard({
  adapterId,
  outputFormat,
  expression,
  ruleEnabled,
  hasSample,
}: {
  adapterId: string;
  outputFormat: string;
  expression: string | null;
  ruleEnabled: boolean;
  hasSample: boolean;
}) {
  const t = useTranslations('outputRule');
  const { toast } = useToast();
  const [pending, startTransition] = useTransition();
  const [format, setFormat] = useState(outputFormat);
  const [rule, setRule] = useState(expression);
  const [enabled, setEnabled] = useState(ruleEnabled);
  const [generating, setGenerating] = useState(false);
  const [rejected, setRejected] = useState<string[]>([]);

  const chooseFormat = (next: string) => {
    const previous = format;
    setFormat(next);
    startTransition(async () => {
      const result = await setOutputFormat(adapterId, next);
      if (!result.success) {
        setFormat(previous);
        toast({ variant: 'error', title: result.error });
      } else {
        toast({ variant: 'success', title: t('formatSaved') });
      }
    });
  };

  const generate = async () => {
    setGenerating(true);
    setRejected([]);
    const result = await generateJsonataRule(adapterId);
    setGenerating(false);
    if (result.success && 'expression' in result) {
      setRule(result.expression ?? null);
      setEnabled(false);
      toast({ variant: 'success', title: t('ruleVerified') });
      return;
    }
    const keys = [
      ...('missingKeys' in result ? (result.missingKeys ?? []) : []),
      ...('differingKeys' in result ? (result.differingKeys ?? []) : []),
    ];
    setRejected(keys);
    toast({ variant: 'error', title: result.error });
  };

  const toggle = () => {
    const next = !enabled;
    setEnabled(next);
    startTransition(async () => {
      const result = await setJsonataEnabled(adapterId, next);
      if (!result.success) {
        setEnabled(!next);
        toast({ variant: 'error', title: result.error });
      } else {
        toast({ variant: 'success', title: next ? t('ruleOn') : t('ruleOff') });
      }
    });
  };

  const remove = () => {
    startTransition(async () => {
      const result = await deleteJsonataRule(adapterId);
      if (!result.success) {
        toast({ variant: 'error', title: result.error });
        return;
      }
      setRule(null);
      setEnabled(false);
      toast({ variant: 'success', title: t('ruleDeleted') });
    });
  };

  return (
    <div className="card p-5 sm:p-6 space-y-6">
      <div>
        <h2 className="font-display text-lg text-cream">{t('title')}</h2>
        <p className="text-sm text-taupe font-accent mt-1">{t('subtitle')}</p>
      </div>

      {/* Output format */}
      <div className="flex flex-wrap items-center gap-3">
        <span className="text-sm text-sand font-accent">{t('formatLabel')}</span>
        <div className="inline-flex items-center gap-0.5 p-0.5 bg-roast border border-bark rounded-lg">
          {FORMATS.map((f) => (
            <button
              key={f.id}
              type="button"
              onClick={() => chooseFormat(f.id)}
              disabled={pending}
              className={`px-3 py-1.5 rounded-md text-xs font-accent uppercase transition-all duration-200 ${
                format === f.id
                  ? 'bg-amber text-espresso font-semibold'
                  : 'text-taupe hover:text-cream'
              }`}
            >
              {f.label}
            </button>
          ))}
        </div>
        <span className="text-xs text-taupe font-accent">{t('formatHelp')}</span>
      </div>

      {/* Deterministic rule */}
      <div className="border-t border-bark pt-5 space-y-3">
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div className="min-w-0">
            <h3 className="font-display text-base text-cream">{t('ruleTitle')}</h3>
            <p className="text-sm text-taupe font-accent mt-1 max-w-xl">{t('ruleHelp')}</p>
          </div>
          {rule && (
            <label className="flex items-center gap-2 shrink-0">
              <span className="text-xs text-taupe font-accent">{t('ruleToggle')}</span>
              <input
                type="checkbox"
                checked={enabled}
                onChange={toggle}
                disabled={pending}
                className="w-4 h-4 accent-[#d4a853]"
                aria-label={t('ruleToggle')}
              />
            </label>
          )}
        </div>

        {rule ? (
          <>
            <pre className="code-block whitespace-pre-wrap break-words max-h-56 overflow-y-auto text-xs">
              {rule}
            </pre>
            <div className="flex flex-wrap items-center gap-3">
              <button
                type="button"
                onClick={generate}
                disabled={generating || pending}
                className="btn-secondary text-xs py-1.5 px-3"
              >
                {generating ? t('generating') : t('regenerate')}
              </button>
              <button
                type="button"
                onClick={remove}
                disabled={pending}
                className="text-xs text-coral hover:underline font-accent"
              >
                {t('delete')}
              </button>
              <span
                className={`text-xs font-accent ${enabled ? 'text-sage' : 'text-taupe'}`}
              >
                {enabled ? t('stateOn') : t('stateOff')}
              </span>
            </div>
          </>
        ) : (
          <div className="flex flex-wrap items-center gap-3">
            <button
              type="button"
              onClick={generate}
              disabled={generating || pending || !hasSample}
              className="btn-primary text-xs py-2 px-4"
            >
              {generating ? t('generating') : t('generate')}
            </button>
            {!hasSample && (
              <span className="text-xs text-coral font-accent">{t('needSample')}</span>
            )}
          </div>
        )}

        {rejected.length > 0 && (
          <p className="text-xs text-coral font-accent">
            {t('rejectedKeys', { keys: rejected.join(', ') })}
          </p>
        )}
      </div>
    </div>
  );
}
